apiVersion: v2
name: mosdac-ai-navigator
description: A Helm chart for MOSDAC AI Knowledge Navigator
type: application
version: 1.0.0
appVersion: "1.0.0"

keywords:
  - ai
  - knowledge-graph
  - satellite-data
  - mosdac
  - isro

home: https://github.com/gravitasops/mosdac-ai-navigator
sources:
  - https://github.com/gravitasops/mosdac-ai-navigator

maintainers:
  - name: GravitasOps Team
    email: team@gravitasops.com
    url: https://gravitasops.com

annotations:
  category: AI/ML
  licenses: MIT
