# Staging values for MOSDAC AI Navigator
global:
  storageClass: "gp2"

app:
  environment: staging

backend:
  replicaCount: 2
  
  ingress:
    hosts:
      - host: staging-api.mosdac-ai.com
        paths:
          - path: /
            pathType: Prefix
            
  resources:
    limits:
      cpu: 2000m
      memory: 4Gi
    requests:
      cpu: 500m
      memory: 2Gi
      
  autoscaling:
    minReplicas: 2
    maxReplicas: 5

frontend:
  ingress:
    hosts:
      - host: staging.mosdac-ai.com
        paths:
          - path: /
            pathType: Prefix
            
  env:
    - name: REACT_APP_API_URL
      value: "https://staging-api.mosdac-ai.com"

postgresql:
  primary:
    persistence:
      size: 200Gi
    resources:
      limits:
        cpu: 4000m
        memory: 8Gi
      requests:
        cpu: 1000m
        memory: 2Gi

redis:
  master:
    persistence:
      size: 50Gi
    resources:
      limits:
        cpu: 1000m
        memory: 4Gi
      requests:
        cpu: 500m
        memory: 2Gi

neo4j:
  core:
    persistentVolume:
      size: 200Gi
    resources:
      cpu: "4"
      memory: "16Gi"
